spring:
  application:
    name: config-server
  profiles:
    active: git
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
        git:
          uri: https://github.com/t-log/forConfigServer.git
          search-paths: licensingservice #ideally every service config should be placed in their respective folders
          default-label: develop
#        vault:
#          port: 8200
#          host: 127.0.0.1
#          kv-version: 2
#          token: myroot
server:
  port: 8071
encrypt:
  key: UsLGJJxELdrD43kKsDcMMcW7xr53HOpt5Eyb83H1cHA=

#Enable all Spring Boot Actuator endpoints.
management:
  endpoints:
    web:
      exposure:
        include: "*"
#logging:
#  level:
#    root: debug
